"""Add dealer and car specification fields

Revision ID: 40f711b6842c
Revises: 
Create Date: 2025-10-05 12:23:50.242853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f711b6842c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_ads_raw', sa.Column('dealer_name', sa.String(length=255), nullable=True))
    op.add_column('car_ads_raw', sa.Column('dealer_type', sa.String(length=50), nullable=True))
    op.add_column('car_ads_raw', sa.Column('fuel_type', sa.String(length=50), nullable=True))
    op.add_column('car_ads_raw', sa.Column('transmission', sa.String(length=50), nullable=True))
    op.add_column('car_ads_raw', sa.Column('body_type', sa.String(length=50), nullable=True))
    op.add_column('car_ads_raw', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('car_ads_raw', sa.Column('engine_power', sa.Integer(), nullable=True))
    op.add_column('car_ads_raw', sa.Column('engine_displacement', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_ads_raw', 'engine_displacement')
    op.drop_column('car_ads_raw', 'engine_power')
    op.drop_column('car_ads_raw', 'color')
    op.drop_column('car_ads_raw', 'body_type')
    op.drop_column('car_ads_raw', 'transmission')
    op.drop_column('car_ads_raw', 'fuel_type')
    op.drop_column('car_ads_raw', 'dealer_type')
    op.drop_column('car_ads_raw', 'dealer_name')
    # ### end Alembic commands ###

