"""Add detected_color fields to CarAdEnriched

Revision ID: 3777eb07e199
Revises: 6b7fb424ec8f
Create Date: 2025-10-05 16:55:51.853181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3777eb07e199'
down_revision = '6b7fb424ec8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_ads_enriched', sa.Column('detected_color', sa.String(length=50), nullable=True))
    op.add_column('car_ads_enriched', sa.Column('detected_color_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_ads_enriched', 'detected_color_confidence')
    op.drop_column('car_ads_enriched', 'detected_color')
    # ### end Alembic commands ###

