"""Add local_image_paths field

Revision ID: 6b7fb424ec8f
Revises: 40f711b6842c
Create Date: 2025-10-05 13:04:34.293093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7fb424ec8f'
down_revision = '40f711b6842c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_ads_raw', sa.Column('local_image_paths', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_ads_raw', 'local_image_paths')
    # ### end Alembic commands ###

